/**
 * Answers API requests from a captured snapshot, for the static demo build only.
 *
 * Nothing here is reachable in the normal build: the only import of this module sits in a
 * branch Vite folds to `false` (`lib/api.ts`), so the adapter and `demo/snapshot.json`
 * are both dropped from the bundle that ships in the wheel.
 *
 * **What the snapshot is.** `demo/snapshot.json` is generated by capturing real responses
 * from the real server, serving real runs produced by `mlexp demo`. It is not written by
 * hand and it is not filled in from what a screen "should" show. This application has had
 * fabricated UI data removed from it three times; a demo carrying invented numbers would
 * put the same defect back in the most visible place in the repository.
 *
 * **The file's shape.**
 *
 * ```json
 * {
 *   "capturedAt": "2026-08-16T09:12:44Z",
 *   "source": "mlexp demo, captured from GET http://127.0.0.1:5000",
 *   "routes": {
 *     "/api/dashboard":                    { "json": { "success": true, "data": [] } },
 *     "/api/run/abc123/logs":              { "json": [] },
 *     "/api/run/abc123/metrics/export":    { "text": "epoch,loss\n", "contentType": "text/csv; charset=utf-8" },
 *     "/api/run/abc123/provenance":        { "status": 404, "json": { "message": "No provenance recorded" } }
 *   }
 * }
 * ```
 *
 * One entry per path. `json` or `text`, never both; `status` defaults to 200, so a route
 * the real API answered with an error is captured with its real status and real body
 * rather than omitted. A path with no entry at all is a 404 in the `{"message": ...}`
 * shape the server uses, which is what the components are already written against.
 *
 * **Query parameters are not part of the key.** Only two routes take any: `logs`
 * (`level`, `limit`, `offset`) and `metrics/export` (`format`). The snapshot stores the
 * unfiltered log once and this module does the filtering and paging itself, matching the
 * server's semantics — snapshotting the combinations would multiply the file for no gain.
 * A key *may* still carry a query string as an escape hatch: an exact match on
 * path-plus-query wins over the bare path, which is how a second `format` of the export
 * would be captured if one is ever wanted.
 */

import rawSnapshot from '../demo/snapshot.json?raw';

/** One captured response. `json` or `text`, not both. */
interface SnapshotEntry {
  /** HTTP status the real server answered with. Defaults to 200. */
  status?: number;
  /** The parsed body, for everything that returns JSON. */
  json?: unknown;
  /** The body verbatim, for the CSV export and any other non-JSON route. */
  text?: string;
  /** Overrides the response's `Content-Type`. */
  contentType?: string;
}

interface DemoSnapshot {
  /** When the responses were captured, ISO-8601, or `null` before anything has been. */
  capturedAt: string | null;
  /** How they were captured, in one line, for the demo banner. */
  source: string;
  routes: Record<string, SnapshotEntry>;
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

/**
 * The snapshot is imported as text and parsed once rather than imported as a module.
 * A run's metrics and logs make this the largest thing in the demo bundle by a wide
 * margin, and one `JSON.parse` of a string beats making the JavaScript parser walk an
 * object literal of the same size.
 */
const snapshot: DemoSnapshot = (() => {
  const empty: DemoSnapshot = { capturedAt: null, source: '', routes: {} };
  try {
    const value: unknown = JSON.parse(rawSnapshot);
    if (!isRecord(value)) return empty;
    return {
      capturedAt: typeof value.capturedAt === 'string' ? value.capturedAt : null,
      source: typeof value.source === 'string' ? value.source : '',
      routes: isRecord(value.routes) ? (value.routes as Record<string, SnapshotEntry>) : {},
    };
  } catch {
    // A snapshot that will not parse leaves every route 404ing, which the UI already
    // renders as an error state. It must not take the whole page down with it.
    return empty;
  }
})();

/**
 * Path keys, normalised.
 *
 * Call sites are not consistent about encoding — `RunSwitcher` wraps the experiment id in
 * `encodeURIComponent` and the four other callers of the same endpoint do not — so a
 * project named `my project` arrives both as `my%20project` and as `my project`. Decoding
 * both the keys and the lookups means the two spellings land on one entry instead of one
 * of them 404ing for no reason a user could see.
 */
const routes = new Map<string, SnapshotEntry>();
for (const [key, entry] of Object.entries(snapshot.routes)) {
  if (isRecord(entry)) routes.set(normaliseKey(key), entry as SnapshotEntry);
}

function decodeSegment(segment: string): string {
  try {
    return decodeURIComponent(segment);
  } catch {
    // A stray `%` is a literal `%`, not a reason to fail the request.
    return segment;
  }
}

function normalisePath(pathname: string): string {
  const decoded = pathname.split('/').map(decodeSegment).join('/');
  return decoded.length > 1 && decoded.endsWith('/') ? decoded.slice(0, -1) : decoded;
}

/** Query parameters sorted, so the key does not depend on the order a caller wrote them. */
function canonicalQuery(search: string): string {
  const params = [...new URLSearchParams(search).entries()];
  params.sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));
  return params.map(([name, value]) => `${name}=${value}`).join('&');
}

function normaliseKey(key: string): string {
  const cut = key.indexOf('?');
  if (cut === -1) return normalisePath(key);
  const query = canonicalQuery(key.slice(cut + 1));
  const path = normalisePath(key.slice(0, cut));
  return query ? `${path}?${query}` : path;
}

function jsonResponse(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

function notFound(pathname: string): Response {
  // The server's error shape, verbatim (`server/app.py`, `_register_errors`). Components
  // read `res.ok` and then this `message`; anything else here would be a shape they have
  // never been given.
  return jsonResponse({ message: `No demo data was captured for ${pathname}` }, 404);
}

function toResponse(entry: SnapshotEntry): Response {
  const status = typeof entry.status === 'number' ? entry.status : 200;
  if (typeof entry.text === 'string') {
    return new Response(entry.text, {
      status,
      headers: { 'Content-Type': entry.contentType ?? 'text/plain; charset=utf-8' },
    });
  }
  return new Response(JSON.stringify(entry.json ?? null), {
    status,
    headers: { 'Content-Type': entry.contentType ?? 'application/json' },
  });
}

// --------------------------------------------------------------------------------------
// Reads
// --------------------------------------------------------------------------------------

const LOGS_PATH = /^\/api\/run\/[^/]+\/logs$/;

/** The closed level vocabulary, as `storage.read_logs` has it. */
const LOG_LEVELS = new Set(['debug', 'info', 'warning', 'error', 'critical']);

function toInt(value: string | null, fallback: number): number {
  if (value === null) return fallback;
  const parsed = Number.parseInt(value, 10);
  return Number.isNaN(parsed) ? fallback : parsed;
}

/**
 * `level` then `offset` then `limit`, reproducing `Storage.read_logs` exactly.
 *
 * `level` selects one severity and asserts no hierarchy, because the format records none;
 * a level outside the vocabulary matches nothing rather than quietly matching everything,
 * which would show a user precisely the records they asked to be rid of. Offsets are
 * clamped rather than rejected, and a limit of zero or less is no rows — this is a read
 * path, and every unanswerable question here answers with an empty list.
 */
function pageLogs(body: unknown, params: URLSearchParams): unknown[] {
  let records: unknown[] = Array.isArray(body) ? body : [];

  const level = params.get('level');
  if (level !== null) {
    const wanted = level.trim().toLowerCase();
    records = LOG_LEVELS.has(wanted)
      ? records.filter(
          (record) =>
            isRecord(record) &&
            typeof record.level === 'string' &&
            record.level.trim().toLowerCase() === wanted,
        )
      : [];
  }

  const start = Math.max(0, toInt(params.get('offset'), 0));
  const limit = params.get('limit');
  if (limit === null) return records.slice(start);
  const count = toInt(limit, 0);
  return count <= 0 ? [] : records.slice(start, start + count);
}

// --------------------------------------------------------------------------------------
// Writes
// --------------------------------------------------------------------------------------

const RUN_TAGS = /^\/api\/run\/([^/]+)\/tags$/;
const RUN_DESCRIPTION = /^\/api\/run\/([^/]+)\/description$/;
const EXPERIMENT_DESCRIPTION = /^\/api\/experiment\/([^/]+)$/;

function readBody(init?: RequestInit): Record<string, unknown> {
  if (typeof init?.body !== 'string') return {};
  try {
    const value: unknown = JSON.parse(init.body);
    return isRecord(value) ? value : {};
  } catch {
    // Matches `_body` in the server: a body that will not parse is an empty one, and the
    // handler's own field check produces the error.
    return {};
  }
}

/**
 * Apply a field to every copy of a record the snapshot holds.
 *
 * A run appears in its own response, in its experiment's `runs` array, and again inside
 * the dashboard payload; an experiment appears under its id, under `/api/experiment` when
 * it is the latest, and in the dashboard. Editing only the canonical entry would leave a
 * tag that appears on the run page and vanishes from the table next to it.
 *
 * The field is written only where it already exists, so this never invents a key on a
 * shape the API does not put one on — the run summaries inside an experiment carry no
 * description, and they must not sprout one because the demo was clicked.
 */
function patchEverywhere(id: string, field: string, value: unknown): void {
  const visit = (node: unknown, depth: number): void => {
    if (depth > 6 || node === null || typeof node !== 'object') return;
    if (Array.isArray(node)) {
      for (const item of node) visit(item, depth + 1);
      return;
    }
    const record = node as Record<string, unknown>;
    if (record._id === id && field in record) record[field] = value;
    for (const child of Object.values(record)) visit(child, depth + 1);
  };

  for (const entry of routes.values()) visit(entry.json, 0);
}

/** The canonical entry for a resource, or `undefined` if it was never captured. */
function resourceBody(path: string): Record<string, unknown> | undefined {
  const entry = routes.get(path);
  return entry && isRecord(entry.json) ? entry.json : undefined;
}

function writeRunTags(runId: string, body: Record<string, unknown>): Response {
  const tags = body.tags;
  if (!Array.isArray(tags)) return jsonResponse({ message: 'Tags must be an array' }, 400);

  const run = resourceBody(`/api/run/${runId}`);
  if (!run) return jsonResponse({ message: 'Run not found' }, 404);

  run.tags = tags;
  patchEverywhere(runId, 'tags', tags);
  return jsonResponse({ message: 'Tags updated', tags }, 200);
}

function writeDescription(
  path: string,
  id: string,
  missing: string,
  body: Record<string, unknown>,
): Response {
  const raw = body.description;
  if (raw !== undefined && raw !== null && typeof raw !== 'string') {
    return jsonResponse({ message: 'Description must be a string' }, 400);
  }
  // An absent key is an empty description — what clearing the box sends, and what the
  // server stores.
  const description = typeof raw === 'string' ? raw : '';

  const resource = resourceBody(path);
  if (!resource) return jsonResponse({ message: missing }, 404);

  resource.description = description;
  patchEverywhere(id, 'description', description);
  return jsonResponse({ message: 'Description updated', description }, 200);
}

function applyWrite(pathname: string, init?: RequestInit): Response {
  const body = readBody(init);

  const tags = RUN_TAGS.exec(pathname);
  if (tags) return writeRunTags(tags[1], body);

  const runDescription = RUN_DESCRIPTION.exec(pathname);
  if (runDescription) {
    const runId = runDescription[1];
    return writeDescription(`/api/run/${runId}`, runId, 'Run not found', body);
  }

  const experiment = EXPERIMENT_DESCRIPTION.exec(pathname);
  if (experiment) {
    const experimentId = experiment[1];
    return writeDescription(
      `/api/experiment/${experimentId}`,
      experimentId,
      'Experiment not found',
      body,
    );
  }

  return notFound(pathname);
}

// --------------------------------------------------------------------------------------
// Entry point
// --------------------------------------------------------------------------------------

/**
 * Resolve one request against the snapshot.
 *
 * Called only by `apiFetch`. Writes mutate the parsed snapshot in memory and return 200,
 * so an edit visibly takes effect; a reload restores the captured state, which is the
 * honest behaviour of a demo with no server behind it and needs no concealing.
 */
export function resolveDemoRequest(path: string, init?: RequestInit): Response {
  const method = (init?.method ?? 'GET').toUpperCase();
  const cut = path.indexOf('?');
  const pathname = normalisePath(cut === -1 ? path : path.slice(0, cut));
  const search = cut === -1 ? '' : path.slice(cut + 1);

  if (method === 'PATCH') return applyWrite(pathname, init);
  if (method !== 'GET' && method !== 'HEAD') {
    return jsonResponse({ message: `${method} is not available in the demo build` }, 405);
  }

  const query = canonicalQuery(search);
  if (query) {
    const exact = routes.get(`${pathname}?${query}`);
    if (exact) return toResponse(exact);
  }

  const entry = routes.get(pathname);
  if (!entry) return notFound(pathname);

  if (LOGS_PATH.test(pathname)) {
    const status = typeof entry.status === 'number' ? entry.status : 200;
    return jsonResponse(pageLogs(entry.json, new URLSearchParams(search)), status);
  }

  return toResponse(entry);
}

/** When and how the snapshot was captured, for the banner that says this is a demo. */
export function snapshotInfo(): { capturedAt: string | null; source: string } {
  return { capturedAt: snapshot.capturedAt, source: snapshot.source };
}
