import { useEffect, useState } from "react";
import { FiX } from "react-icons/fi";
import { demoSnapshotInfo } from "../../lib/api";
import "./DemoBanner.css";
// Disabled styles for controls the demo can't serve (log and patch downloads). Imported
// here because this component only renders in the demo build.
import "../../demo/demoOnly.css";

/** Where "run it yourself" points. */
const REPO_URL = "https://github.com/VamP08/MLExperimentTracker";

/** Dismissal is remembered for the tab (sessionStorage), not forever. */
const DISMISSED_KEY = "mlexp-demo-banner-dismissed";

/** Matches the collapse transition in DemoBanner.css. */
const LEAVE_MS = 200;

/**
 * Notice at the top of the static demo: no server, real runs, nothing saved, and how to
 * run it locally. Only rendered in the demo build (see VITE_DEMO in App.tsx).
 */
const DemoBanner = () => {
  const [visible, setVisible] = useState(() => {
    try {
      return sessionStorage.getItem(DISMISSED_KEY) !== "1";
    } catch {
      // Private-mode Safari throws on sessionStorage access. Just show the notice.
      return true;
    }
  });
  const [leaving, setLeaving] = useState(false);
  const [capturedAt, setCapturedAt] = useState<string | null>(null);

  // When the snapshot was captured, if known.
  useEffect(() => {
    let cancelled = false;
    demoSnapshotInfo()
      .then((info) => {
        if (cancelled || !info?.capturedAt) return;
        const date = new Date(info.capturedAt);
        if (!Number.isNaN(date.getTime())) setCapturedAt(date.toLocaleDateString(undefined, { dateStyle: "medium" }));
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!leaving) return;
    const timer = window.setTimeout(() => setVisible(false), LEAVE_MS);
    return () => window.clearTimeout(timer);
  }, [leaving]);

  const dismiss = () => {
    try {
      sessionStorage.setItem(DISMISSED_KEY, "1");
    } catch {
      // Not being able to remember the dismissal is not a reason to refuse it.
    }
    setLeaving(true);
  };

  if (!visible) return null;

  return (
    <div
      className={`demo-banner${leaving ? " demo-banner-leaving" : ""}`}
      role="note"
      aria-label="About this demo"
    >
      <div className="demo-banner-inner">
        <span className="demo-banner-tag">Demo</span>

        <p className="demo-banner-text">
          This is a static demo — there is no server behind this page. The data is a snapshot of
          real runs, generated by <code className="demo-banner-code">mlexp demo</code> and captured
          from the real API{capturedAt ? ` on ${capturedAt}` : ""}, then bundled into the page. Nothing you change
          here is saved.{" "}
          <span className="demo-banner-run">
            To use it on your own runs:{" "}
            <code className="demo-banner-code">pip install "mlexperimenttracker[server]"</code>, then{" "}
            <code className="demo-banner-code">mlexp ui</code>. The{" "}
            <a
              className="demo-banner-link"
              href={REPO_URL}
              target="_blank"
              rel="noreferrer noopener"
            >
              README
            </a>{" "}
            shows how to log from a training script.
          </span>
        </p>

        <button
          type="button"
          className="btn btn-icon btn-ghost demo-banner-dismiss"
          onClick={dismiss}
          aria-label="Dismiss this notice"
          title="Dismiss"
        >
          <FiX />
        </button>
      </div>
    </div>
  );
};

export default DemoBanner;
