import { useEffect, useState } from "react";
import "./DemoBanner.css";
// Disabled states for the controls the static demo cannot operate (the log and patch
// downloads). Imported here because this component is the one thing that renders only in
// the demo, so the stylesheet rides in on the demo's module graph and on nothing else.
import "../../demo/demoOnly.css";

/** Where "run it yourself" points. */
const REPO_URL = "https://github.com/VamP08/MLExperimentTracker";

/**
 * Dismissal is remembered for the tab, not forever.
 *
 * sessionStorage rather than localStorage on purpose: a visitor who has read the notice
 * should not have to read it again while clicking around, but the page must not be able
 * to permanently forget that it is telling people what they are looking at.
 */
const DISMISSED_KEY = "mlexp-demo-banner-dismissed";

/** Matches the collapse transition in DemoBanner.css. */
const LEAVE_MS = 200;

/**
 * The notice at the top of the static demo build.
 *
 * The demo is the same dashboard as the real one with its data layer swapped for a
 * snapshot, and that is exactly the sort of thing that reads as fake unless it says what
 * it is. So it says it, above the fold, before anything else: no server, real runs,
 * nothing saved, and the two commands that reproduce it locally.
 *
 * Rendered only by the demo build — see the VITE_DEMO guard in App.tsx.
 */
const DemoBanner = () => {
  const [visible, setVisible] = useState(() => {
    try {
      return sessionStorage.getItem(DISMISSED_KEY) !== "1";
    } catch {
      // Private-mode Safari throws on sessionStorage access. Showing the notice is the
      // safe failure.
      return true;
    }
  });
  const [leaving, setLeaving] = useState(false);

  useEffect(() => {
    if (!leaving) return;
    const timer = window.setTimeout(() => setVisible(false), LEAVE_MS);
    return () => window.clearTimeout(timer);
  }, [leaving]);

  const dismiss = () => {
    try {
      sessionStorage.setItem(DISMISSED_KEY, "1");
    } catch {
      // Not being able to remember the dismissal is not a reason to refuse it.
    }
    setLeaving(true);
  };

  if (!visible) return null;

  return (
    <div
      className={`demo-banner${leaving ? " demo-banner-leaving" : ""}`}
      role="note"
      aria-label="About this demo"
    >
      <div className="demo-banner-inner">
        <span className="demo-banner-tag">Demo</span>

        <p className="demo-banner-text">
          This is a static demo — there is no server behind this page. The data is a snapshot of
          real runs, generated by <code className="demo-banner-code">mlexp demo</code> and captured
          from the real API, then bundled into the page. Nothing you change here is saved.{" "}
          <span className="demo-banner-run">
            To run it on your own runs: clone{" "}
            <a
              className="demo-banner-link"
              href={REPO_URL}
              target="_blank"
              rel="noreferrer noopener"
            >
              the repository
            </a>
            , then <code className="demo-banner-code">pip install -e ".[server]"</code> and{" "}
            <code className="demo-banner-code">mlexp ui</code>.
          </span>
        </p>

        <button
          type="button"
          className="demo-banner-dismiss"
          onClick={dismiss}
          aria-label="Dismiss this notice"
          title="Dismiss"
        >
          &times;
        </button>
      </div>
    </div>
  );
};

export default DemoBanner;
